[workspace.metadata.clippy]
all = true
cargo = true
nursery = true
pedantic = true

[workspace]
members = [
  "x",
  "cdp",
  "live",
  "scp",
  "test",
  "_/screen",
  "_/thread",
  "_/xyloid",
]
resolver = "3"

[profile.release.package."*"]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
opt-level = 3
overflow-checks = false
strip = true

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = "fat"
opt-level = "z"
overflow-checks = false
panic = "abort"
rpath = false
strip = true

[profile.dev.package."*"]
incremental = true
opt-level = 1

[profile.dev]
debug = true
opt-level = 1
