[workspace]
members = [
  "x",
  "cdp",
  "live",
  "scp",
  "test",
  "_/screen",
  "_/thread",
  "_/xyloid",
]
resolver = "3"

[profile.release.package."*"]
strip = "symbols"
split-debuginfo = "none"
overflow-checks = false
opt-level = 3
incremental = true
debug-assertions = false
debug = false
codegen-units = 1

[profile.release]
strip = "symbols"
split-debuginfo = "none"
rpath = false
panic = "abort"
overflow-checks = false
opt-level = 3
lto = "fat"
incremental = true
debug-assertions = false
debug = false
codegen-units = 1

[profile.dev.package."*"]
strip = "none"
overflow-checks = true
opt-level = 0
incremental = true
debug-assertions = true
debug = true
codegen-units = 256

[profile.dev]
strip = "none"
rpath = true
panic = "unwind"
overflow-checks = true
opt-level = 0
lto = false
incremental = true
debug-assertions = true
debug = true
codegen-units = 256
