binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
color = "Always"
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
disable_all_formatting = false
edition = "2024"
empty_item_single_line = false
enum_discrim_align_threshold = 64
error_on_line_overflow = false
error_on_unformatted = false
fn_params_layout = "Compressed"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
generated_marker_line_search_limit = 1
group_imports = "StdExternalCrate"
hard_tabs = false
hex_literal_case = "Lower"
ignore = []
imports_granularity = "One"
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 256
merge_derives = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
required_version = "1.8.0"
short_array_element_width_threshold = 1
show_parse_errors = true
skip_children = false
skip_macro_invocations = []
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_lit_single_line = false
struct_lit_width = 0
struct_variant_width = 0
style_edition = "2024"
tab_spaces = 2
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = false
use_small_heuristics = "Off"
use_try_shorthand = true
where_single_line = true
wrap_comments = false

# struct_field_align_threshold = 256
# single_line_let_else_max_width = 256
# single_line_if_else_max_width = 256
# short_array_element_width_threshold = 0
# inline_attribute_width = 256
# fn_call_width = 256
# doc_comment_code_block_width = 256
# comment_width = 0
# chain_width = 256
# attr_fn_like_width = 256
# array_width = 256

# version = "Two"
# fn_args_layout = "Tall"
# hide_parse_errors = false
# merge_imports = true
