[dependencies]
common = { path = "./../_/common" }

[[bin]]
path = "_.rs"
name = "scp"
doctest = false

[package]
version = "0.0.1"
repository = "https://github.com/hq-zyrosk/scp"
name = "scp"
license = "MIT OR Apache-2.0"
keywords = ["chrome", "client", "devtools", "protocol"]
edition = "2021"
description = "A Chrome DevTools Protocol client"
categories = ["development-tools::debugging"]
authors = ["Zyrosk <hq.zyrosk@gmail.com>"]
