[dependencies]
common = { path = "./../_/common" }
windows = { version = "0.61.3", features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_JobObjects",
  "Win32_System_Threading",
  "Win32_Foundation",
] }

[[bin]]
path = "_.rs"
name = "scp"
doctest = false

[package]
authors = ["Zyrosk <hq.zyrosk@gmail.com>"]
categories = ["development-tools::debugging"]
description = "A Chrome DevTools Protocol client"
edition = "2024"
keywords = ["chrome", "client", "devtools", "protocol"]
license = "MIT OR Apache-2.0"
name = "scp"
readme = "README.md"
repository = "https://github.com/hq-zyrosk/scp"
version = "0.0.1"
