[dependencies]
windows = { version = "0.61.3", features = [
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_Input",
  "Win32_System_Ioctl",
  "Win32_System_IO",
  "Win32_System_Diagnostics_Debug",
  "Win32_Storage_FileSystem",
  "Win32_Security",
  "Win32_Security_Authorization",
  "Win32_Foundation",
  "Win32_Devices_HumanInterfaceDevice",
  "Win32_Devices_DeviceAndDriverInstallation",
] }
common = { path = "./../common" }

[package]
authors = ["Zyrosk <hq.zyrosk@gmail.com>"]
categories = ["development-tools::debugging"]
description = "A Chrome DevTools Protocol client"
edition = "2024"
keywords = ["chrome", "client", "devtools", "protocol"]
license = "MIT OR Apache-2.0"
name = "xyloid"
readme = "README.md"
repository = "https://github.com/hq-zyrosk/main"
version = "0.0.1"

[lib]
doctest = false
path = "_.rs"
